### ISSUE TITLE
Chaining methods from Big constructor

### ISSUE THREAD

**Issue by dorkblue** [MikeMcl/big.js#105]
Hey there,

I've started using big.js to avoid floating point problems in an app that could get relatively big, and deals with numbers like sales value, discount et cetera.

I was wondering if its possible to chain methods straight away from the constructor, instead of having the name a variable first.

IE:
instead of
```
const x = 10
const X = Big(x)

const y = X.times(4)
```

but this
```
const x = 10
const y = Big(x).times(4)
```

**Comment by MikeMcl** [comment]
Yes, of course.

**Comment by dorkblue** [comment]
Thank you.
