### ISSUE TITLE
Error: [big.js] Invalid exponent

### ISSUE THREAD

**Issue by tommedema** [MikeMcl/big.js#106]
I'm trying to compute a naive bayes classifier probability for an observation in a population. See also https://en.wikipedia.org/wiki/Naive_Bayes_classifier#Sex_classification

The right hand side displays Euler's constant to the power of this value:

```
const p0Exponent = Number(
        value
          .minus(summary.mean0)
          .pow(2)
          .times(-1)
          .div(summary.variance0.times(2))
      )
```

Which in my case is `-0.0382040358548183`

When I then run:

```
const valueP0 = summary.nbcMultiplier0.times(bigEuler.pow(p0Exponent))
```

I get:

```
Error: [big.js] Invalid exponent
```

Why is this exponent of ~-0.0382 invalid ?

Also, why does `.pow` require a number, and not a Big instance?

**Comment by MikeMcl** [comment]
See #74
