### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by mickeyvip** [MikeMcl/big.js#11]
It would be nice to have an ability to format a number with decimal + thousands separators:

100000 -> 100,000
12345.345 -> 12,345.345

thank you

**Comment by lukescott** [comment]
This would be useful to have in the library. The bignumber.js library has this - but it also has a lot more that may not be required, such as different bases, etc.

**Comment by MikeMcl** [comment]
I tend to agree, but how far to go? 

*bignumber.js* has 

```js
FORMAT = {
  decimalSeparator: '.',
  groupSeparator: ',',
  groupSize: 3,
  secondaryGroupSize: 0,
  fractionGroupSeparator: '\xA0',
  fractionGroupSize: 0
};
```

but that seems too complex for this library.

How about just having a second parameter to `toFixed`, for example

```js
var n = new Big('12345678.91234');
n.toFixed();            // '12345678.91234'
n.toFixed(true);        // '12,345,678.91234'
n.toFixed(2);           // '12345678.91'
n.toFixed(2, true);     // '12,345,678.91'
```

or, by adding further properties to the `Big` constructor

```js
var n = new Big('12345678.91234');
n.toFixed(2);            // '12345678.91'

Big.decimalSeparator = ',';
Big.thousandsSeparator = ' ';

n.toFixed(2);           // '12 345 678,91'
```

**Comment by lukescott** [comment]
I think toFixed already has an established meaning, so adding a format aspect to it would be inconsistent, especially when considering the other libraries.

Since big.js doesn't have a `toFraction` function, you could do a FORMAT just like bignumber.js, but only include the decimal and thousands parts. So `toFormat([dp])` to match big.js's `toFixed([dp])` - bignumber.js has `toFixed([dp[, rm]])` and `toFormat([dp[, rm]])`.

Otherwise I liked the version you posted above. I used this variation:

```javascript
Big.prototype.toFormat = function (dp, ts = ",", ds = ".") { // ES6 defaults
	var arr = this.toFixed(dp).split(".");
	arr[0] = arr[0].replace(/\B(?=(\d{3})+(?!\d))/g, ts);
	return arr.join(ds);
};
```

**Comment by MikeMcl** [comment]
I've decided not to add the method here, but instead I've published it as an extension to this library and to *decimal.js*.

See https://github.com/MikeMcl/toFormat

**Comment by lukescott** [comment]
How do you use this with ES6 import statements?

**Comment by lukescott** [comment]
Might make sense to do something like:
```javascript
import {format} from "format";
var num = Big(123);
format(num);
````
Basically doing something external that understands Big/Decimal.

**Comment by MikeMcl** [comment]
I haven't played with ES6 imports yet, but it's something I want to look at.

**Comment by vizcay** [comment]
Hi, It will be great to document the existense of that extension library in the README.. I've ended up using BigDecimal for a project just because I needed this method.. and after a while I've found this, too late for me...

Thanks for the library anyway!
