### ISSUE TITLE
Mistake in docs

### ISSUE THREAD

**Issue by 8084** [MikeMcl/big.js#112]
> http://mikemcl.github.io/big.js/#mod
> mod.mod(n) ⇒ Big
> Throws if n is negative or otherwise invalid.

It surely does not throw on negative values.

 ```
> new Big(42).mod(-10).toString()
'2'
```

**Comment by MikeMcl** [comment]
Thanks for the report.
It should be "Throws if n is zero or otherwise invalid."
I will correct this presently, or you could submit a pull request if you like.

**Comment by 8084** [comment]
#113
