### ISSUE TITLE
toPrecision variant that does not add zeros

### ISSUE THREAD

**Issue by klntsky** [MikeMcl/big.js#114]
It would be nice to have an option to bypass adding zeros [here](https://github.com/MikeMcl/big.js/blob/master/big.js#L277). 

What if we have dp = 1e6, and the value passed is just 0? We end up adding 1e6 zeros, which consumes a lot of time and may be pointless for most usage scenarios.

Also, I think that pushing constant value within cycle here (and in some other places in the code) is not the best way of doing this in sense of performance. You should consider rewriting it to something like

```
      // Append zeros?
      var d = k - x.c.length;
      if (d > 0) x.c = x.c.concat(new Array(d).fill(0));
```

Also2, why there are two nearly identical files, `big.js` and `big.mjs`? It is possible to translate es2015 modules to commonjs (e.g. with [babel](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-commonjs)), so it may be useful to add the translation command to the build script and deal with just one file instead of two.

**Comment by 8084** [comment]
> I am not clear what you mean here. Where is dp from

Uh, I've meant `sd`, not `dp`, sorry. `sd` as an argument of `.toPrecision`

I was wondering if there is a way to stringify a value with maximum possible precision, but without padding it with `0`s. The resulting string should end with the last significant digit if it is possible, or be very long (1e6 decimal places) otherwise.

There are cases when it's known that some number does not contain repetends, but it's exact length in decimal places is not known.

I ended up with guessing the number of decimal places, like this:

```
function (big) {
    return big.toFixed(big.c.length + Math.abs(big.e))
            .replace(/\.?0+$/, '');
};
```

**Comment by MikeMcl** [comment]
> I was wondering if there is a way to stringify a value with maximum possible precision, but without padding it with 0s.

What's wrong with `toString()`, or `toExponential()` if you don't want trailing integer-part zeros?

If you want to be able to specifiy the maximum number of significant digits you could add the following method, 

```js
Big.prototype.precision = function (sd) {
  let r = new Big(this);
  let len = r.c.length;
  if (len > sd) {
    len = sd;
    while (r.c[len - 1] === 0 && len > 1) --len;
    r.c.length = len;
  }
  return r;
};
```
Then use as

```js
let x = new Big('999.1234000056789');
x.precision(7).toString();    // '999.1234'
x.precision(10).toString();   // '999.1234'
x.precision(12).toString();   // '999.123400005'
```

Swap `toString()` for `toFixed()` if you never want exponential notation.

**Comment by 8084** [comment]
@MikeMcl thanks! This is exactly what I needed, `toString()` with configurable `sd`.

**Comment by MikeMcl** [comment]
Added a `prec` method in *v6.0.0*, to round a Big number to a specified precision.
