### ISSUE TITLE
toFixed include RM as parameter

### ISSUE THREAD

**Issue by nutboltu** [MikeMcl/big.js#117]
It would be a good addition if we add RM(round mode) as parameter in `toFixed` function same as `round` function.

Feature Request:

`.toFixed(dp, rm) ⇒ string`

**Comment by Stazis555** [comment]
Rounding mode is not used by toFixed() but documentation state otherwise: 
![image](https://user-images.githubusercontent.com/2266017/88192832-ab7b0f80-cc45-11ea-8f76-d2aedc7ac849.png)

source [documentation](https://mikemcl.github.io/big.js/)

**Comment by MikeMcl** [comment]
@Stazis555 

Yes, it is.

```js
x = new Big(0.1);
Big.RM = 0;      // ROUND_DOWN
x.toFixed(0);    // "0"
Big.RM = 3;      // ROUND_UP
x.toFixed(0);    // "1"
```

**Comment by nutboltu** [comment]
@MikeMcl it's a feature request. Can we add RM as the second parameter of `toFixed` same as `round` function?

**Comment by MikeMcl** [comment]
Okay, I'll try and do it this week.
