### ISSUE TITLE
How to improve Big() constructor without forking? (question)

### ISSUE THREAD

**Issue by vizcay** [MikeMcl/big.js#121]
I want to improve the big constructor so it accepts "," as decimal separator and ignores them. For example `Big('1,234.50')` and `Big(100).plus('1,000.50')` shall not raise and exception and parse correctly.

I'am using Big.js (and toFormat) with webpack and babel for ES2016 compatibility. So I'm doing `import { Big } from 'big.js'` etc.

Sorry, JS is not my main language so this may be a simple question.

**Comment by MikeMcl** [comment]
No, it is not simple. As a starting point:

```js
const stripCommas = n => String(n).replace(/,/g, '');

class B extends Big {
 
  constructor(n) {
    super(stripCommas(n));
  }
 
  plus(n) {
    return super.plus(stripCommas(n));
  }
}

// Example

let x = new B('1,000,000');
let y = x.plus('999,999.12345');

console.log(y.toString());    // "1999999.12345"
```

Including `div` would involve having to work around the problem that calling `super.div` will use `Big.DP` not `B.DP`, so:

```js
class B extends Big {
 
  constructor(n) {
    super(stripCommas(n));
  }
 
  plus(n) {
    return super.plus(stripCommas(n));
  }
  
  div(n) {
    Big.DP = B.DP;
    Big.RM = B.RM;
    return super.div(stripCommas(n));
  }
}

B.DP = Big.DP;
B.RM = Big.RM;
```

Ultimately, it will be quite complicated and I do not think it will be worth doing.
It would be much simpler to just use something like

```js
Big(100).plus(stripCommas('1,000.50'))
```

or 

```js
Big.fromString = function (s) {
  return Big(s.replace(/,/g, ''));
};

let x = Big(100);
let y = Big.fromString('1,000.50');
let z = x.plus(y);
console.log(z.toString());    // "1100.5"
```

**Comment by swftvsn** [comment]
Also remember that this is locale specific, so one should take into account, that in some countries comma `,` is the decimal separator and the thousand separator is a space ` ` etc. Those must anyway be parsed using the specific locale. 

IMHO any string logic in this library is not needed as it's a separate problem domain. ( The formatting of numbers. For an example see https://github.com/osrec/currencyFormatter.js )

**Comment by vizcay** [comment]
@MikeMcl :

Thanks for your reply, ended up doing this:

```
import Big from 'big.js'
import toFormat from 'toformat'

toFormat(Big)

String.prototype.toBig = function() {
  return new Big(this.replace(/,/g, ''))
}

export default Big
```

Still, I believe a simple extension point should be provided for this.

@swftvsn: this has nothing to do with locales, because we are asuming standard english rules which dictate that '.' is the decimal separator and ',' thousands.

**Comment by swftvsn** [comment]
@vizcay Then this is for sure application specific, as this library can't make assumptions about locale.

**Comment by vizcay** [comment]
@swftvsn of course a specific locale is assumed, since is parsing "." as decimal separator. What I say is just to support it completely anyway.
