### ISSUE TITLE
Initializing `void 0` or `undefined` doesn't throw `Invalid number` Error

### ISSUE THREAD

**Issue by Thammachart** [MikeMcl/big.js#127]
Using `Big(void 0)` or `Big(undefined)` doesn't throw Invalid Number Error,

but `new Big(void 0)` does

Environments:
- Arch Linux
- `nvm`
- Node v10.16.3

```Javascript
const Big = require('big.js')

const foo1 = Big(undefined)   // No Error thrown
const foo2 = Big(void 0)      // No Error thrown

const foo3 = Big('20')

try {
  const bar2 = foo1.plus(foo3)   // `foo1.plus is not a function` Error
} catch(error) { console.error('Caught', error.message) }

try {
  const bar1 = foo3.plus(foo1)   // `Invalid number` Error
} catch(error) { console.error('Caught', error.message) }

try {
  const foo4 = new Big(void 0)   // `Invalid number` Error
} catch(error) { console.error('Caught', error.message) }
```

Result:
```
Caught foo1.plus is not a function
Caught [big.js] Invalid number
Caught [big.js] Invalid number
```

**Comment by MikeMcl** [comment]
See the [FAQ](http://mikemcl.github.io/big.js/#multiple).

**Comment by Thammachart** [comment]
If this is the case:
```Javascript
const payload = extractFromUnpredictablePayload()
const foo1 = Big(payload.bar1)  // payload.bar1 could be undefined
```

The code like this would be solved by either:
- Checking whether if parameter is defined first
- Or, using `new Big(...)` to explicitly throw the error

Can you confirm this?

**Comment by MikeMcl** [comment]
Yes, I can confirm that they are appropiate solutions.

**Comment by PachowStudios** [comment]
Just experienced this behavior for the first time. I think this should be explained in the documentation in the same part where it says that using `new` is optional so it's clear that there is a difference.

**Comment by MikeMcl** [comment]
@PachowStudios 

So do I.
