### ISSUE TITLE
Should JavaScript add a BigDecimal type?

### ISSUE THREAD

**Issue by littledan** [MikeMcl/big.js#129]
We're investigating this question in TC39, and we'd like to build off of the experience you have accumulated in decimal.js, big.js and bignumber.js. There's a very early [proposal draft](https://github.com/littledan/proposal-bigdecimal), and we're trying to collect feedback from existing library work in [this issue](https://github.com/littledan/proposal-bigdecimal/issues/22). Any help will be appreciated!

**Comment by nycdotnet** [comment]
neat!

**Comment by MikeMcl** [comment]
Apoligies for the delay in my response.

> Should JavaScript add a BigDecimal type?

No. See [#31](https://github.com/littledan/proposal-bigdecimal/issues/31).

If it was to happen I would recommend that it be similar to Python's decimal module and my [decimal.js](https://github.com/MikeMcl/decimal.js).
