### ISSUE TITLE
nth root function

### ISSUE THREAD

**Issue by raybiez** [MikeMcl/big.js#13]
How about extending the library with a nthroot function... Currently I'm extending mine with:

``` javascript
P['nthrt'] = P['nthroot'] = function (n)
{
    var x = this, negate, approx;

    // Convert n to a Big
    n = new Big(n);

    // Checking to see if root is negative
    negate = n.mod(2) == 1 && x['s'] == -1;

    if (negate)
        x = x.times(-1);

    // Initial nth root result (nth root = x to the power of 1 / n)
    approx = x.pow(Big(1).div(n));

    // Validating result & return
    n = approx.pow(n);
    if (x.minus(n).abs(x - n) < 1 && (x > 0 == n > 0))
        return negate ? approx.times(-1) : approx;
};
```

Calculation is based on the contents of an article at http://cwestblog.com/2011/05/06/cube-root-an-beyond/

**Comment by travellingprog** [comment]
@raybiez You must wonder why you're getting an update on a 3 year old post, but this saved my butt. I'm converting a bunch of stuff in my code from JavaScript numbers to using Big instances, and I realized there was one module where we were calculating a cubic root. The precision didn't need to be high, but the input could certainly be beyond JS's safe maximum number. Very relieved to have come across this, works for me!

**Comment by danday74** [comment]
big.js does not support .pow(1/3)
however, it's cousin lib ... decimal.js-light ... does

To get around this painful aspect of big.js I've used the 2 libs in tandem as follows:

```
const Big = require('big.js')
const Decimal = require('decimal.js-light')

const nthRoot = (bigNumber, intRoot) => {
  const strBigNumber = bigNumber.toFixed()
  const decimal = Decimal(strBigNumber)
  const root = decimal.pow(1 / intRoot)
  return Big(root.toFixed())
}

module.exports = nthRoot

```
