### ISSUE TITLE
Internal representation - BigInt

### ISSUE THREAD

**Issue by sla100** [MikeMcl/big.js#133]
As I can see the libraries is based on the internal representation of sign, string mantissa and numerical exponent. Both Node and modern browsers support the new BigInt type that could replace the character and the mantissa. Elemental operations will then be faster than based on strings. Have you considered refactoring in this style yet?

**Comment by MikeMcl** [comment]
The library does not use strings for internal representation, and I am committed to keeping it ECMAScript 3 compatible.

**Comment by sla100** [comment]
OK. I have not seen this guarantee
