### ISSUE TITLE
Entering a number beginning with + throws an `Invalid Number` error

### ISSUE THREAD

**Issue by kesupile-kesupile** [MikeMcl/big.js#135]
**Steps to reproduce**

Call the `Big` constructor with a number beginning with +:

```javascript
import Big from 'big.js';
const n = Big('+2')
```

**Expected Result**
The library recognises that `+2` is a valid number and treats it as it would `2`

**Actual Result**

```
Error: [big.js] Invalid number
```

**Proposed solution**
1. Allow the parsing of integers with a + prefix as standard
2. Make this an option that can be passed to the constructor

**Comment by benfletcher** [comment]
Has been previously discussed in #70.

**Comment by kesupile-kesupile** [comment]
Thanks for your prompt response
