### ISSUE TITLE
Difference between big-js and big.js

### ISSUE THREAD

**Issue by majovanilla** [MikeMcl/big.js#136]
Hello!

I am working on a project and one of my code reviewers requested I installed big-js instead of big.js.

I used this [page](https://www.npmjs.com/package/big-js) as a reference and as you can see there, the first line gives the command `npm i big-js` but below I could also find `npm install big.js`

My logic says that both are the same, but if I check my JSON file I can see that running both commands gives me a different result.
 ```
"big-js": "^3.1.3",
"big.js": "^5.2.2"
```

So, which one should I use? And what's the difference between them?

Thanks a lot!

**Comment by nycdotnet** [comment]
big-js appears to be an old fork of this library; the page you linked on npm indicates it hasn’t been updated in 5 years.  Chances are you will want to use the library here (big.js) rather than the fork, as this version is maintained, unless you’re having a problem that the fork claims to fix.

**Comment by majovanilla** [comment]
@nycdotnet thanks for your reply. 

I realized that one of the reasons for using big-js was that big.js shows a linter error when importing the package to the file because we have the `"import/extensions" set to ` "js": "never"`.

I will suggest a change to the project's linter file and favor the use of big.js

Thank you for your answer.
