### ISSUE TITLE
[Rquest feature] Static methods for comparison

### ISSUE THREAD

**Issue by fspezi** [MikeMcl/big.js#137]
The library allow to execute a comparison between 2 `Big` values using the method of first one, and put the second as argument of method:

```js
var a = Big(100);
var b = Big(5);
var areEquals = a.eq(b);
```

There are circustances where `a` and/or `b` can be `nothing`. Then a static comparison method versions are very useful.  
Then instead of do this:  

```js
var areEquals = !a && !b
  ? true
  : !a || !b
    ? false
    : a.eq(b);
```

...it is possible to do this:

```js
var areEquals = Big.eq(a, b);
```

**Comment by MikeMcl** [comment]
Yes, that could be useful.

I would probably go with

```js
Big.eq = (a, b) => { try { return Big(a).eq(b) } catch { return false } };
```

But I don't want to add any further methods, thanks, static or otherwise.

**Comment by fspezi** [comment]
Perfect, good!

Maybe, can `a` and `b` to be "equals" when they are "null" / "nothing" together?
