### ISSUE TITLE
Error in round with very small numbers

### ISSUE THREAD

**Issue by MyPluppie** [MikeMcl/big.js#139]
Im getting an error when using `round()` with very small numbers.

```
DP = 30
RM = 1
MAX_DP = 1E6
MAX_POWER = 1E6
NE = -10
PE = 10

x = '1e-20'
y = Big( x ).round( 10, 1 ).toString();

```
error: 
`reference to undefined property "-9"
`
in this part of `round()`:
```
var xc = x.c,
      i = x.e + dp + 1;  // -20 + 10 + 1 = -9
if (rm === 1) {
    // xc[i] is the digit after the digit that may be rounded up.
    more = xc[i] >= 5;  //<< error
} else if (rm === 2) {
```
It happens on any number where `x.e + dp < -1` like 
`1e-12` and `0.000000000001`

**Comment by MikeMcl** [comment]
Well, I've just opened a browser console at the documentation [page](http://mikemcl.github.io/big.js/) and entered

```js
 Big.DP = 30; Big.RM = 1; Big.NE = -10; Big.PE = 10;
 Big('1e20').round(10, 1).toString() 
```
and the result is as expected:  ``` "1e+20" ```

I cannot reproduce your error. Any suggestions?

**Comment by MikeMcl** [comment]
After further investigation, I assume this is Firefox-only **warning** which is reported only if the **javascript.options.strict** preference (not the same as JavaScript's strict mode) is set to true (perhaps by a browser extension).

**Comment by MikeMcl** [comment]
I refactored the `round` function in *v6.0.0* so I do not think this warning will be produced anymore.
