### ISSUE TITLE
Incorrect result of chained operations

### ISSUE THREAD

**Issue by flmg** [MikeMcl/big.js#141]
Hello guys, I'm having trouble with a chained series of operations:
````
+new Big(1).div(1609.344).mul(1609.344)
1
+new Big(1).div(1000).div(1609.344).mul(1609.344).mul(1000)
0.9999999999999936
````
The second result should equal 1 too, is there anything that I'm doing wrong? 🤔 

Thanks!

**Comment by flmg** [comment]
Sorry, I realised I had to increase the maximum number of decimal places
```
Big.DP = 30
30
+new Big(1).div(1000).div(1609.344).mul(1609.344).mul(1000)
1
```

**Comment by legend80s** [comment]
how do I set the `DP`? 30 40 or the bigger the better?

**Comment by legend80s** [comment]
```
var Big = require("big.js")

// "0.99999999999999999999"
Big('1').div('3').times('3').toString()

// 1
Big('1').div('3').times('3').toNumber()
```

why toString no got `"1"` which is more human-reasonable.
