### ISSUE TITLE
Error in times method

### ISSUE THREAD

**Issue by JenTechSystems** [MikeMcl/big.js#145]
I put this in browser console on the [docs page](https://mikemcl.github.io/big.js) and the answer is incorrect - it should be 13800

`Big(65.71428571428571).times(Big(210)).toString()
"13799.9999999999991"`

**Comment by MikeMcl** [comment]
No, the answer is correct.

 The last digit of `65.71428571428571` is `1`, so the answer must end in `1` when multiplying by a multiple of 10.

**Comment by JenTechSystems** [comment]
Yes, that makes sense. Let me take a step back...

I'm really trying to perform this calculation:

x = 210 * (460/7)
x/210 = (460/7)
7x/210 = 460
7x = 460 * 210
7x = 96600
x = 96600 / 7
x= 13800

I put this into the docs page console like this:

new Big(210).times(new Big(new Big(460).div(7))).toString()

Which gives:

"13799.9999999999999999991"

Am I doing something wrong?

**Comment by MikeMcl** [comment]
```javascript
Big.DP = 20;
new Big(460).div(7).toString();    // "65.71428571428571428571"
Big.DP = 50;
new Big(460).div(7).toString();    // "65.71428571428571428571428571428571428571428571428571"
```

**Comment by JenTechSystems** [comment]
I'm not sure what to make of that...

Can you please explain?
