### ISSUE TITLE
Error ROUND_HALF_EVEN?

### ISSUE THREAD

**Issue by ibruque** [MikeMcl/big.js#149]
We are facing the next problem:
![Screenshot 2020-12-21 at 17 39 36](https://user-images.githubusercontent.com/633590/102802695-57708480-43b7-11eb-9a24-a52b1d6c397e.png)
We understand first case is correct, but the second one should be `3.77`, right? Are we missing something?

**Comment by MikeMcl** [comment]
I don't know why you think the result should be `3.77` and not `3.78`, when the rounding mode is `ROUND_HALF_EVEN` and `7` is odd and `8` is even.

**Comment by ibruque** [comment]
@MikeMcl ok, I understand the behavior now. Is there any way to perform `ROUND_HALF_DOWN` rounding?

**Comment by MikeMcl** [comment]
Not really, no.
