### ISSUE TITLE
Suggestion: Add static constants for RoundingMode

### ISSUE THREAD

**Issue by Semigradsky** [MikeMcl/big.js#150]
It will be much easier than remember what `0`, `1`, `2`, `3` means.

Proposed type definition:
```ts
export const enum RoundingMode {
    RoundDown = 0,
    RoundHalfUp = 1,
    RoundHalfEven = 2,
    RoundUp = 3,
}
```

Example of usage: https://codesandbox.io/s/magical-frog-qgxi9?file=/src/index.ts:71-83
```js
import Big, { RoundingMode } from "big.js";

alert(Big(0.444).round(2, RoundingMode.RoundUp));
```
---
Related `d.ts` issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29864

~~Looks like `enum RoundingMode` was added to library type definition by mistake.~~

**Comment by MikeMcl** [comment]
If you are using the Typescript definitions from DefinitelyTyped then the enum should be available for use in your code.

**Comment by MikeMcl** [comment]
The `RoundingMode` enum in the type definitions works just fine.

As is often the case, this is a TypeScript project configuration issue, not an issue with this library. 

Here is a zip file containing your test case.

[ts_test.zip](https://github.com/MikeMcl/big.js/files/5758814/ts_test.zip)

Just run `tsc test.ts` and then `node test.js`.

**Comment by bobvandevijver** [comment]
Works just fine might be a bit fast... There are scenarios where the current type definitions do not work, for example within Babel (see the linked issue and the Babel linked issue within that). It looks like that Babel has a mismatch with `tsc` on this feature, which probably won't be solved anytime soon. 

If there is anything that can be done to improve portability, I believe this library can benefit from it. At this time, I am forced to redefine these constants in my own project in order to make it work. I used the following as that allowed for the best optimization in the compiled result:

```js
import {RoundingMode} from 'big.js';

const RoundDown: RoundingMode = 0;
const RoundHalfUp: RoundingMode = 1;
const RoundHalfEven: RoundingMode = 2;
const RoundUp: RoundingMode = 3;

export {RoundDown, RoundHalfUp, RoundHalfEven, RoundUp};
```

**Comment by MikeMcl** [comment]
@bobvandevijver 

If you gave any evidence that the type definitions "do not work" where they can reasonably be expected to then please provide code that demonstrates this, preferably by providing a zip file of a minimal failing test case and its dependencies.

**Comment by Semigradsky** [comment]
Babel doesn't support `const enums` because those require type information to compile. See https://github.com/babel/babel/issues/8741

**Comment by MikeMcl** [comment]
Okay, so it is a matter of supporting Babel and of providing constants for the convenience of all users whether Babel users or not. Yes?

I could add, for example
```js
Big.RoundDown = 0;
Big.RoundHalfUp = 1;
// etc.
```
here, but I considered that originally and decided not to as this is a minimalist library.

I am not sure I want to go to the trouble of adding these static constants then updating the docs and type definitions, and writing tests and releasing a new version etc.. when TypeScript users can just use the existing type definitions and other users can simply add the constants themselves if they want them. 

It's a close call... I probably should do it... someone could make a PR and I'd probably accept it.

**Comment by Semigradsky** [comment]
> and I don't understand why you think that the enum looks like it was added by mistake

Sorry about this, I didn't notice that this is `const enum` =)

**Comment by MikeMcl** [comment]
Added static rounding mode constants in *v6.1.0*.

```js
Big.roundDown
Big.roundHalfUp
Big.roundHalfEven
Big.roundUp
```

Thanks for the suggestion.

**Comment by bobvandevijver** [comment]
I created a PR to update the typings for this change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52610
