### ISSUE TITLE
Suggestion: Add an optional fallback method for failed division.

### ISSUE THREAD

**Issue by Thrasymachus01** [MikeMcl/big.js#151]
It's a very common occurrence when developing UI to have zero division before the initialization case - for example, a number input will typically start as 0 before a user inputs another value.

To guard against this a very simple pattern is used:
```
const result = num1.gt(0) && num2.gt(0) ? num1.div(num2) : 0;
```

This pattern is so common that it has gotten to the point of copy+paste.
A nice solution, taking inspiration from rust, is to have a `div_or` method. For example:

```
const result = num1.div_or(num2, 0);
// If it's valid division then return num1 / num2 else return 0
```

It may even be more convenient to just have the zero default inbuilt as a method:

```
const result = num1.div_or_zero(num2);
```

**Comment by MikeMcl** [comment]
Interesting.

I like it, but this is a minimalist library and there is a very high bar to adding any further methods, which I don't think this quite reaches.

If a user wants to add a `div_or_zero` method I would suggest:

```js
Big.prototype.div_or_zero = function (n) {
  return this.c[0] && (n = new Big(n)).c[0] ? this.div(n) : new Big(0);
};
```

Thanks for your input.
