### ISSUE TITLE
Add a `Big.nullable(value)` method

### ISSUE THREAD

**Issue by sparebytes** [MikeMcl/big.js#155]
I appreciate that `Big(x)` throws when x is null/undefined but there are times I know I'm working with a value that may be nullable and want to fail gracefully. `Big.nullable(value)` makes it a bit easier to work with javascript's new null coalescing and optional chaining operators.

```
// simple case - not a huge benefit
return x == null ? Big(x).toFixed(2) : "Not set"
return Big.nullable(x)?.toFixed(2) ?? "Not set

// with optional chaining
return data?.user.rating == null ? Big.nullable(data.user.rating) .toFixed(2): "N/A";
return Big.nullable(data?.user.rating)?.toFixed(2) ?? "N/A";
```

See also #32

**Comment by MikeMcl** [comment]
If I am understanding you correctly, then the implementation would just be 

```js
Big.nullable = x => x == null ? x : Big(x);
```  

Yes?

**Comment by sparebytes** [comment]
Exactly!

**Comment by sparebytes** [comment]
The typescript def would look something like this
```ts
interface Big {
  nullable(value: BigSource): Big;
  nullable(value: null): null;
  nullable(value: undefined): undefined;
}
```
