### ISSUE TITLE
Add Big.zero method?

### ISSUE THREAD

**Issue by janzenz** [MikeMcl/big.js#159]
Hi thank you for this library. Is it worth to add a `Big.zero` method to make a fallback for invalid Big numbers? Pretty much like #155 At the moment we're doing something like this
```
function toBig(value) {
  try {
    return Big(value);
  } catch(e) {
    return Big(0);
  }
}
```
or something inline like:
```
totalPrice.reduce((acc, cur) => {
  if (!acc) return acc;

  return Big(acc).plus(cur);
}, 0);
```

So far so good. However, I find it more concise and quicker if we have something like `Big.zero` to always default to 0-value instead of throwing an error, i.e. `Big.zero(null).plus(12.345)`. Is that something worth to add?

**Comment by MikeMcl** [comment]
I don't want to add a `zero` method for everybody, but the correct implementation would be:

```js
Big.zero = x => { 
  if (x !== undefined) try { return Big(x) } catch { };
  return Big(0);
};
```

because the Big constructor currently returns a new Big constructor if `undefined` is passed.

I would be quite happy to return `null` instead of throwing but that would mean I would have to add a check for null to all the prototype methods.

I think users can just add a `nullable` or `zero` method themselves as it suits.

Thanks for the suggestion.

**Comment by janzenz** [comment]
Thank you for the clarification @MikeMcl and for sending me to the right direction. I'm not sure if this is related to the topic but do you have any idea or workaround on how to fail gracefully when chaining methods?

For example, the function below fails if `cur` is either `null` or `''`:
```
priceList.reduce((acc, cur) => {
  return Big(acc).plus(cur);
}, 0)
```
I guess if I were to use `Big.zero` or something I would imagine any method chained with it will always fall back to `0`. Is that something would be worth exploring?

**Comment by MikeMcl** [comment]
Yes, you could use for example:

```js
priceList.reduce((acc, cur) => Big(acc).plus(Big.zero(cur)))
// or
priceList.reduce((acc, cur) => Big(acc).plus(cur || 0))
// etc.
```

It depends on the possible values within the `priceList`.

**Comment by janzenz** [comment]
Thanks for that example that's pretty neat.

I was imagining more like:
```
Big.zero(acc).plus(cur)
```
With being initialized as `Big.zero` all the chained methods hopefully would follow suit and default everything else as `0`.

I'm imagining if I have to initialize all the values passed to the chained methods will make the code a bit messy, e.g.
```
const getTotalPercentage = (percentage) => priceList.reduce((acc, cur) => Big.zero(acc).plus(Big.zero(cur)).div(Big.zero(percentage || 100));
// or
const getTotalPercentage = (percentage) => priceList.reduce((acc, cur) => Big.zero(acc || 0).plus(cur || 0).div(percentage || 100));
```
With method chaining inheriting from `Big.zero` default I'm imagining it would look like this:
```
const getTotalPercentage = (percentage) => priceList.reduce((acc, cur) => Big.zero(acc).plus(cur).div(percentage));
```

**Comment by MikeMcl** [comment]
> With being initialized as Big.zero all the chained methods hopefully would follow suit and default everything else as 0.

I don't see how that could happen.

Can't you just iterate through `priceList` beforehand using `map` or `filter` and get the values as an array of Bigs.  

```js
priceList = priceList.filter(x => { try { return new Big(x) } catch { } });
```
