### ISSUE TITLE
Cannot get correct result when giving a number

### ISSUE THREAD

**Issue by sofiaps** [MikeMcl/big.js#160]
When I try something like that:

var x = new Big(9999999999999.99999).round(5).toFixed(5);

the x always rounds up to '10000000000000.00000'.

If I give it as a string it works fine ( i.e. new Big('9999999999999.99999') gives in fact '9999999999999.99999')

**Comment by MikeMcl** [comment]
```js
console.log(9999999999999.99999);    // 10000000000000
