### ISSUE TITLE
toFixed() crashes browser tab on values greater than Infinity 

### ISSUE THREAD

**Issue by HermenegildoMI** [MikeMcl/big.js#161]
**Given**
String value that is a number and is larger than MAX_VALUE / Infinity

**Expected**
Big.js throws an exception and does not compute any further calculations since this is not a "safe" number

**Reality**  
Big.js accepts string value without error and should a developer call `toFixed()`, function crashes browser tab. 

Example: 

```tsx
const num = new Big("528256e40000640005774827"); // executes without errors

num.toFixed(); // crashes browser tab
```

**Comment by MikeMcl** [comment]
The maximum recommended exponent value of a Big is 1000000, but this is not checked as this is a minimalist library not designed to work with such improbably large values.

My other big number libraries do include include such checks, but here a user can easily implement their own if required by looking at the `e` property of a Big.
