### ISSUE TITLE
Factorial numbers

### ISSUE THREAD

**Issue by mazunki** [MikeMcl/big.js#162]
I'm currently working on permutations, and thus big numbers appear, and the need for factorials. 

We probably know of the built-in limitations to factorial numbers being 12! and 20! for 32-bit and 64-bit numbers, and 171! for JavaScript.

Needless to say, a standard for `1..N` for-loop yields a O(n²) complexity, so it is not too straightforward to implement, unless proper effort and care is done.

There are methods such as the Stirling function, amongst others, which allow effective operation of factorials. Is there a chance such a function/approximation could be added to the library?

Otherwise, would you recommend using another library instead?

**Comment by benfletcher** [comment]
The big.js [readme suggests](https://github.com/MikeMcl/big.js#features):

> The little sister to [bignumber.js](https://github.com/MikeMcl/bignumber.js/) and [decimal.js](https://github.com/MikeMcl/decimal.js/). See [here](https://github.com/MikeMcl/big.js/wiki) for some notes on the difference between them.

I'd recommend checking those out perhaps. There's also the native BigInt in JavaScript.

**Comment by MikeMcl** [comment]
>  Is there a chance such a function/approximation could be added to the library?

No, I don't think so.

I second Ben's suggestion to use BigInt.
