### ISSUE TITLE
Support for util.inspect() via [util.inspect.custom] (feature request) (node.js)

### ISSUE THREAD

**Issue by anders8** [MikeMcl/big.js#164]
In node.js, I prefer util.inspect() over JSON.stringify() for viewing objects while debugging. Big.js objects show up as their full object.

Sample code:

> 
>            let dSample=Big(1.23)
>            console.log(`JSON.stringify: ${JSON.stringify(dSample)}`)
>            console.log(`util.inspect  : ${util.inspect(dSample)}`)

Result:
>JSON.stringify: "1.23"
>util.inspect  : Big {
>  s: 1,
>  e: 0,
>  c: [ 1, 2, 3 ],
>  constructor: [Function: Big] {
>    DP: 4,
>    RM: 1,
>    NE: -7,
>    PE: 21,
>    strict: false,
>    Big: [Circular],
>    default: [Circular]
>  }
>}

This looks fixable by adding a formatting property to the object according to the node.js util docs here:
https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects
which seems like it wouldn't be much more than
[util.inspect.custom](depth, options) 
and setting it to the existing .stringify()

I did write a custom inspector to see if a reasonable fix could be be done outside the project, but the difficult comes with recursion, getting into the arrays you end up blowing up the stack, so a simple, working version is this for any visiting the thread, but note it doesn't handle anything inside arrays:

>function customInspect(depth,opts){
>    var result = `{\n`
>    for (var key in this)
>        {
>        let strConstructorFunctionName=this[key].constructor.name.substring(0,3)
>        result += `  [${strConstructorFunctionName}] `;
>        switch(strConstructorFunctionName)
>            {
>            case 'Big':
>                result += key + ` : ${this[key].toString()}\n`;
>                break
>            default:
>                result += key + ' : '+ util.inspect(this[key]) +`\n`
>                break
>            }
>        }
>    result += `}\n`
>    return result;
>    };
>
>transaction['test']=Big(1.23)
>transaction[util.inspect.custom]=customInspect
>console.log(,`object ${util.inspect(transaction)}`)

Also note that you have add the [util.inspect.custom]=customInspect property to any object you want this to be formatted this way.

But, and I see the trouble in advance, this is an issue for node.js only, I don't think browsers even have the util.inspect functions, although they do have a similar inspect class.

I welcome any discussion. 😁

**Comment by MikeMcl** [comment]
Yes, I added this to decimal.js a while ago. Not sure if I want to add it here.

```js
Big.prototype[Symbol.for('nodejs.util.inspect.custom')] = Big.prototype.toString;
```

**Comment by anders8** [comment]
Well Mike, that's pretty awesome, thanks man! ❤❤❤

For anyone else following along, the line Mike put above can go in your source file, without any need to mess with the node module. I put mine right below the " import { Big } from 'big.js' " and it worked perfectly. 👍
