### ISSUE TITLE
TODO Update typescript definitions re static rounding mode constants

### ISSUE THREAD

**Issue by MikeMcl** [MikeMcl/big.js#166]

**Comment by message** [comment]
Consider adding rounding modes to Big.RoundingMode as in [@types/big.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/big.js/index.d.ts) instead of directly to Big constructor

**Comment by MikeMcl** [comment]
I prefer them added to the Big constructor. 

`Big.RoundingMode.RoundUp` is too verbose for this library.
