### ISSUE TITLE
Big.js gives Error(INVALID + 'number'); for new Big(Infinity), in strict mode false

### ISSUE THREAD

**Issue by balamurugansd** [MikeMcl/big.js#171]
Error: [big.js] Invalid number
Even when the strict mode is false,

```
const Big = require('big.js');

Big.strict = false;

const value = new Big(Infinity);

console.log(value)
```

How to handle Infinity numbers during BigJS calculation 

eg: Assume I do a calc (a**a +1 ) and the value of a is 123456789, it gives me error at new Big(Infinity),

**Comment by MikeMcl** [comment]
Infinity is not a valid value for a Big number.

**Comment by balamurugansd** [comment]
Big.strict = false; Will it not handle @MikeMcl

**Comment by MikeMcl** [comment]
No.
