### ISSUE TITLE
big.strict does not exist on type 'BigConstructor'.ts

### ISSUE THREAD

**Issue by joshxyzhimself** [MikeMcl/big.js#172]
Just noticed this

```js

// @ts-check

const n = require('big.js').default;

n.strict = true; // Property 'strict' does not exist on type 'BigConstructor'.ts(2339)
n.RM = n.roundDown;
n.DP = 20;

module.exports = n;
```

References

- http://mikemcl.github.io/big.js/#strict
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/big.js/index.d.ts

**Comment by MikeMcl** [comment]
Thanks for the notification.

Someone should make a PR to DefintelyTyped. 

I am not [responsible](https://github.com/MikeMcl/big.js#typescript) for the definitions file there and I don't want to get involved just now.
