### ISSUE TITLE
toNumber error

### ISSUE THREAD

**Issue by Ex-Caliburn** [MikeMcl/big.js#175]
new Big(260).times(100).toNumber()

Uncaught TypeError: (intermediate value).times(...).toNumber is not a function

version: 6.1.1

**Comment by MikeMcl** [comment]
If `toNumber` isn't a function then you aren't using *v6.1.1*.

**Comment by thm912** [comment]
Same here. 

Deleted the node_modules directory and re-installed the package 6.1.1

**Comment by MikeMcl** [comment]
*v6.1.1* is incorporated into the documentation page [here](http://mikemcl.github.io/big.js/), so a moment's testing at the console shows `toNumber` is present.

If you have a genuine error, please add a zip file of a directory containing the test code and node_modules folder and I will take a look.

**Comment by thm912** [comment]
Problem solved. We had also "@types/big.js" in our package.json, which we forgot to update.

**Comment by Ex-Caliburn** [comment]
Deleted the node_modules directory and re-installed the package 6.1.1
is okay
