### ISSUE TITLE
Provide npm minified distribution files

### ISSUE THREAD

**Issue by cdalexndr** [MikeMcl/big.js#176]
Please add `big.min.js` to npm

**Comment by MikeMcl** [comment]
Sorry for the late reply but I no longer want the responsibility and maintenance burden of providing a minified version so I won't be publishing one myself.

I provide an [example](https://github.com/MikeMcl/big.js#minify) of how the module can be minified in the *README* and an already minified version is available from, for example, [jsdelivr](https://cdn.jsdelivr.net/npm/big.js@6.1.1/big.min.js).
