### ISSUE TITLE
Feature request: .negate() operator to flip the sign

### ISSUE THREAD

**Issue by anders8** [MikeMcl/big.js#177]
Yes, it's certainly simple enough to do myBigVar.times(-1) 

But multiplication seems like overkill when all we want to do is have an API for getting to the .s element to toggle it.

Your efforts are very much appreciated! I like this library! 👍

**Comment by MikeMcl** [comment]
It's a reasonable request and I will consider it. In the meantime, it's as simple as 

```js
myBigVar.s = -1
```

If anyone wants to add such a method after importing the library, the correct implementation is: 

```js
Big.prototype.neg = function () {
  var x = new this.constructor(this);
  x.s = -1;
  return x;
};
```

**Comment by anders8** [comment]
I was thinking:

```
Big.prototype.negate = function () {
  var x = new this.constructor(this);
  x.s = (~x.s)+1;
  return x;
};
```

This would turn 1 into -1 but also turn -1 into 1. Since it only used a bitwise NOT and an add, it would be super fast.

Tiny test:
https://jsfiddle.net/ghebw10y/

.neg to force negative and .negate to flip sign?  As always, it's your baby, and thanks for the work you put in. 😎

**Comment by MikeMcl** [comment]
@anders8 

Oh, you're right. My implementation is not correct. It should be `x.s = -x.s`. I'm going to edit it above.

Thanks for the correction.

**Comment by anders8** [comment]
*forehead smack* 
-x.s, of course. Let the compiler do whatever optimizations it deems necessary. Old habits over here.

**Comment by MikeMcl** [comment]
Added `neg` method in *v6.2.0*.
