### ISSUE TITLE
Documentation generator

### ISSUE THREAD

**Issue by mdeckebach** [MikeMcl/big.js#179]
Not a bug, just a question but I couldn't find another way to get in touch. What tool are you using to generate your API documentation (https://mikemcl.github.io/big.js/)? It's one of the cleanest, easy-to-follow resources I've come across. Thanks.

**Comment by MikeMcl** [comment]
No too lwas used in writing the documentation. I just kept it simple and improved it over time.

Thanks for the feedback.
