### ISSUE TITLE
can we have big number truthiness: if(bignumber) ... instead of conversion and then checking

### ISSUE THREAD

**Issue by metayash** [MikeMcl/big.js#180]
hi, I'll elaborate.
lets say I have a ```const x = Big("5")```
Is there a way I can check for truthiness directly, something like..
```if(x)``` instead of ```if(Number(x.toString())) then...```

**Comment by MikeMcl** [comment]
I don't understand what you mean. Are you referring to checking if the value of a Big number is zero?

**Comment by aster2709** [comment]
just how you can check to truthiness of a number, ```if(5)``` <- this condition will be true, or a string ```if("")``` this condition will be false, but to put a big number inside if condition, we first need to covert it to string or number, and then check. hope that could be simplified. hope i make sense

**Comment by MikeMcl** [comment]
@aster2709 

> just how you can check to truthiness of a number

All big numbers are truthy, and all numbers are truthy except zero, so I am still unclear what you mean.

I ask again: Are you referring to checking if the value of a Big number is zero?

> to put a big number inside if condition, we first need to covert it to string or number, 

Why?

**Comment by ymxhta** [comment]
yes basically it, how do I check if the value is equal to 0

**Comment by MikeMcl** [comment]
To check if the value of a Big number is not zero:

```js
if (!x.eq(0))
// or
if (x.c[0] !== 0) 
// or
if (x.c[0]) 
```

Or 

```js
Big.prototype.isNotZero = function () { return !!this.c[0] };

if (x.isNotZero()) {
```

**Comment by metayash** [comment]
ok thank you!
