### ISSUE TITLE
Uncaught ReferenceError: Big is not defined

### ISSUE THREAD

**Issue by amjad756** [MikeMcl/big.js#183]
I get this error whenever I try to use the package from a script tag in HTML. I am using big.js as part of a laravel app.

I have downloaded the package then compiled it into a public app.js file which is linked to in the head section of the HTML file. However, when I try to use Big i get a reference error saying Big is not defined. If I use the cdn it works fine. I am wondering why the package is not working though.

**Comment by MikeMcl** [comment]
Sorry, I don't know anything about laravel.

**Comment by amjad756** [comment]
Thanks a lot for the reply. I have recreated the same problem without laravel in this repository
https://github.com/amjad756/big.js-test
I have only included big.js and I link my html to the compiled app.js but i still get the same error when I try to use the library within html script tags which is not the issue when I link html directly to cdn. There must be something obvious that I am missing.
