### ISSUE TITLE
Circular dependency leads to error when recursively accessing enumerable properties

### ISSUE THREAD

**Issue by OleksandrZaturskyi** [MikeMcl/big.js#184]
At the moment, `Big` instances have a constructor property that refers to `Big`, which makes it difficult to recursively iterate over the instance properties(opentelemetry tracing is my case).
![image](https://user-images.githubusercontent.com/41697979/144832109-cb9e4648-da6d-4c1d-922e-a7abaaf9bb20.png)
Is it possible to define `constructor` as not `enumerable` in order to allow recursive introspection for own properties? e.g.
```
Object.defineProperty(x, "constructor", { value: Big, enumerable: false });
```

**Comment by MikeMcl** [comment]
Yes, it is.
