### ISSUE TITLE
[Feature Request] Static properties for Comparisons

### ISSUE THREAD

**Issue by intellix** [MikeMcl/big.js#185]
I'm working on a typescript nrwl/nx codebase that compiles with Babel/SWC and requires isolatedModules enabled. This means you cannot import const enums from @types/big.js like RoundingMode or Comparison.

I've been able to replace **RoundingMode.RoundDown** with **Big.roundDown** but I don't have something similar for Comparisons like potentially Big.GT or Big.greaterThan.

I'd either have to create my own enum or put numbers directly into my codebase like so.

**Before:**
```ts
if (payout.cmp(maxPayout) === Comparison.GT) {
```

**After:**
```ts
if (payout.cmp(maxPayout) === 1) {
```

**Comment by MikeMcl** [comment]
Okay, I'll consider it.

```js
if (payout.gt(maxPayout)) {
```
