### ISSUE TITLE
TS7016: Could not find a declaration file for module 'big.js'

### ISSUE THREAD

**Issue by shlomich** [MikeMcl/big.js#190]
Hiya, when running the project I am running into this problem since there is no declaration file.

TS7016: Could not find a declaration file for module 'big.js'. 'C:/Users/rrrr/Desktop/rrrr/rrrr/git/rrrr/node_modules/big.js/big.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/big.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'big.js';`
    2 | import {pg} from 'pg'
    3 | import type {PairInfo} from '@rrrr/rrrr/types';
  > 4 | import Big from 'big.js'

Ofcourse // @ts-ignore fixes it but I was wondering if there's something you can do in order to get it fixed. Thanks :)

Should I use your other lib? https://github.com/MikeMcl/bignumber.js ?

**Comment by shlomich** [comment]
I have only came across this because  I have faced a "original: TypeError: (0 , big_js_1.default)(...).toNumber is not a function" :(.

**Comment by MikeMcl** [comment]
As per the [README](https://github.com/MikeMcl/big.js#typescript):

```
$ npm install --save-dev @types/big.js
```
