### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by JcDenton86** [MikeMcl/big.js#196]
Hi,

<img width="209" alt="image" src="https://user-images.githubusercontent.com/1433320/193112829-b4a40b41-5348-45c5-8202-df70958d6cad.png">

On the image above the formula is: 
```
const numerator = new Big(1);
const denominator = new Big(12);
const amount = numerator.div(denominator).times(600).round(4,2).toNumber(); // 49,98
```
which gives the result 49,98 €. 

However if I replace the above with:
```
const amount  = (1 / 12) * 600; // 50
```
the result is 50 € which is the wanted result.

I have tried many combinations of the round(dp, rm) function, but none of them gives the correct result. 

What am I missing?

Thank you in advance

**Comment by MikeMcl** [comment]
Your example results in `50` not `49,98` at the default `Big.DP` setting.
