### ISSUE TITLE
Support for Comparision operators

### ISSUE THREAD

**Issue by paritosh64ce** [MikeMcl/big.js#198]
Can we have comparison operators (greaterThan, lessThan) support?

This library is definitely better alternative as compared to decimals.js as it supports more decimal precision except this one thing: [comparedTo](https://mikemcl.github.io/decimal.js/#cmp) operator

**Comment by MikeMcl** [comment]
I don't know know what you mean by "supports more precision".

Anyway, there is a [cmp](http://mikemcl.github.io/big.js/#cmp) method, if that is what you are looking for.

**Comment by paritosh64ce** [comment]
It helps, thanks!

BTW, what I meant is this: while doing simple addition and subtraction, with big.js, I get more precise values of the result. Have a look at below screenshots (I used `object.toPrecision(50)` method).

With big.js
![image](https://user-images.githubusercontent.com/13868399/212251497-1930347c-6098-403f-ae47-b395344ce067.png)

With decimal.js
![image](https://user-images.githubusercontent.com/13868399/212251624-9eb92a32-6999-4498-81d1-b4c57d69d9f4.png)
