### ISSUE TITLE
Add the toSignificantDigits method

### ISSUE THREAD

**Issue by litao9238** [MikeMcl/big.js#205]
Can you add the _**toSignificantDigits**_ method to Big.js
Just like **Decimal.js**
Examples: 

Decimal.config({ precision: 5, rounding: 4 })
x = new Decimal(9876.54321)

x.toSignificantDigits()                          // '9876.5'
x.toSignificantDigits(6)                         // '9876.54'
x.toSignificantDigits(6, Decimal.ROUND_UP)       // '9876.55'

**Comment by MikeMcl** [comment]
See the [prec](http://mikemcl.github.io/big.js/#prec) method.
