### ISSUE TITLE
isBig() method

### ISSUE THREAD

**Issue by tommilimmot** [MikeMcl/big.js#36]
```js
var Big = require('big.js');

var n = new Big('534.45');

console.log(n instanceof Big);
```

This works mostly: in browser and node. But breaks in tests. Apparently ```instanceof``` isn't very reliable.

It would be great, if one could ```console.log(Big.isBig(n)); ```

**Comment by MikeMcl** [comment]
Please could you further explain the tests that you are performing. If `Big` is in  scope, then any big number created from it will be an `instanceof Big` within that scope.

**Comment by tommilimmot** [comment]
Sure. I'm running the tests in terminal with [Jest](https://github.com/facebook/jest), which is built on top of Jasmine. I wanted to detect all Big.js values, so we can use the ```cmp``` method to compare them instead of string/number comparison. So, I used ```value instanceof Big```, and it worked in the browser but not in the tests, i.e. ```console.log``` prints ```true``` while running the app in the browser, ```false``` while running the tests in terminal.

I figured, it might have something to do with [```instanceof``` not working across multiple contexts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_(e.g._frames_or_windows)). I'm not actually aware how the Jest/Jasmine internals work, so I don't know why. By the way, I'm using ```jest.autoMockOff()```, so that Jest doesn't mock Big.js, which could've caused this.
 But anyway, I replaced the check with lodash's

```js
_.isObject(value) && _.isFunction(value.cmp)
```

A convenience method would be nice to have in these cases. At least [```moment.isMoment()```](https://github.com/moment/moment/blob/94ad539f965689289af54b6493abca0a65ab4ce6/moment.js#L2149) seems to have a fallback for ```instanceof```.

**Comment by tommilimmot** [comment]
Ah, so that was the problem! We use Browserify. So we need to ```require('big.js')``` for each module, and the module that tries to identify Big instances isn't the one that created it.

So, this has nothing to do with Jest/Jasmine, but the fact that we don't run Browserify as part of our test task. The browser gets the same Big even though it's required again, but the test runner gets another Big. My bad, sorry for wasting your time.

Anyway, I understand your reluctance to add the method. But I still think that it would be a nice-to-have feature.

**Comment by MikeMcl** [comment]
Yes, maybe. I'll consider it further.

    Big.prototype.name = '[object Big]';
    Big.isBig = function (obj) {return obj && obj.name === '[object Big]';};

**Comment by Xotic750** [comment]
Added a `Big.isBig` method to my [fork](https://github.com/Xotic750/big.js). Not written any tests for it yet but have tested it on [jsFiddle](http://jsfiddle.net/Xotic750/rf12t7qt/) and all appears well.

**Comment by subos2008** [comment]
I would also like to see this. I'm leaving this here for people to +1 with the emoji.
