### ISSUE TITLE
Round of negative value greater than -1 gives a result of `0`

### ISSUE THREAD

**Issue by Xotic750** [MikeMcl/big.js#43]
When I run the following code,

`new Big(-0.4).round(0).toString()`

I get a string value of `0` and I was expecting `-0`.

The tests seem to suggest that you would expect that too.

`T(-0, -0.4);`

Although, String(-0) will give `0` and so `0` === '0' -> pass.

But I wonder if you really meant?

`T('-0', -0.4);`

Which would give `0` === '-0̈́` -> fail.

I was hoping that you could clarify the situation?

**Comment by MikeMcl** [comment]
As with JavaScript numbers, calling `toString` on minus zero, will result in `0` not `-0`, but the value of the Big will actually be minus zero as can be seen from

    new Big(-0.4).round(0).s    // -1

**Comment by Xotic750** [comment]
Ok, got you. It's more a problem with the method of testing rather than the Big. I forgot about taking a look at the actual property to see what that was indicating. I didn't know that Big's `toString` method intentionally mimicked Javascript's `-0.toString()` result. I see in the tests that you normally use the private `isMinusZero` function when you are being specific, but in this case you did not, so that left me wondering. Thank's for the quick reply.

**Comment by Xotic750** [comment]
I am wondering if it would make sense to have `valueOf`, which returns the same as `toString`, represent the value of the `Big('-0')` as `-0`?

**Comment by MikeMcl** [comment]
String type or number type?

Clearly, `valueOf` needs to return the same type each time, and I chose long ago that it needs to be string because of the usual precision loss in the conversion to number, which means that a returned number would not accurately represent the 'value of' a Big.

So, if you're suggesting `valueOf` return the string `'-0'`, then yes that's an option, although strictly it would break backward compatibility because `toString` would no longer return the same as `valueOf`... i.e. it would mean the major version number would need to be incremented.

I notice that `(-0).valueOf()` returns `-0` (number type) on the browsers I've just checked, and `0` (number type) in Node.js.

**Comment by Xotic750** [comment]
Yes, I meant `valueOf` to return the string `-0`. It's just at present, other than looking at the properties of Big, there is no way to preserve this information - unless another method was added to the class. Anyway, it's just a suggestion. :)

**Comment by MikeMcl** [comment]
Yes, I think it makes sense, and I will probably make the change to bignumber.js and decimal.js also if I make it here.

**Comment by Xotic750** [comment]
If you are going to do this then it may well be worth thinking about the `toJSON` method too, would it be best to use the `valueOf` or `toString` representation. I'm thinking the `valueOf`?

**Comment by Xotic750** [comment]
Added this ability along with tests to my [fork](https://github.com/Xotic750/big.js), if it is of any interest. :)

**Comment by MikeMcl** [comment]
I see that travis is keeping you busy :)  

And yes, I think that `toJSON` should use `valueOf` to preserve the signed zero.

**Comment by Xotic750** [comment]
Yeah, that and some strange bug on node 0.6 in multiply that I don't understand, but managed to fix it by just changing how the code was written, (y.s * zero) changed to an if..else. Weird! :)

**Comment by Xotic750** [comment]
The `valueOf` preservation of `-0` made it into BigNumber.js, but I was just wondering if you plan to do the same in Big.js?

https://github.com/MikeMcl/big.js/blob/master/big.js#L877

**Comment by MikeMcl** [comment]
@Xotic750 

I'll have a look at this later this week.

**Comment by MikeMcl** [comment]
@Xotic750 

Okay, `valueOf` now returns `'-0'` for negative zero, which is clearly the right thing to do.
Thanks for the nudge.
