### ISSUE TITLE
Add supported browsers list

### ISSUE THREAD

**Issue by fisch42** [MikeMcl/big.js#46]
Please add a list of the supported browsers in the README. Does big.js work in old IEs, especially IE8?

**Comment by MikeMcl** [comment]
That would be a long list. 

It will work in any browser supporting ECMA-262 3rd edition, i.e. any 21st century browser, including IE 6+. I have IE 6 on a virtual machine and I've just tested it again and its works fine although the div.js test took about 45 seconds to complete. I believe I have have tested it on all IE versions in the past, using some tool or other, but I didn't document it so I cannot be certain.

I haven't had any reports of it not working anywhere. In theory it would be good to have a comprehensive list of all JavaScript engines and browsers on which it had been tested, but I do not have the time, resources or desire to do that myself.

**Comment by nycdotnet** [comment]
You must have a really fast computer.  I just did the same test in IE 6 on a VM and all tests passed, but div took 84 seconds and the total test runtime was 247 sec.  IE 11 on same machine (not in VM) took 5; pretty amazing what 15 years of JS optimization work can do.
