### ISSUE TITLE
Allow RM and DP to be specified per function or instance

### ISSUE THREAD

**Issue by defunctzombie** [MikeMcl/big.js#49]
The RM and DP properties are global to all instances. If a user wishes to use a specific rounding mode or precision for a single operation (to which those properties apply) they would need to save any previous value, set the new value, and then reset the old value. If their operation has multiple async steps then they would need to be careful to do this every time.

It would make such use safer if it was possible to specify these settings on a per operation level. Originally I thought on a per instance could make sense too, but since it really is isolated to the operation that is where I would start. Possibly as an options argument to the related function calls.

Happy to do the PR but wanted to get some perspective on why these were global in the first place (possibly some benchmark or design reason).

Thoughts?

Related documentation:
http://mikemcl.github.io/big.js/#dp

**Comment by defunctzombie** [comment]
Note: I have read the [Errors](http://mikemcl.github.io/big.js/#Errors) section and still think that there might be value in specifying this per operation if possible/practical.

**Comment by MikeMcl** [comment]
Do you mean the *How can I simultaneously use different decimal places and/or rounding mode settings for different Big numbers?* section at the bottom of the [FAQ]( http://mikemcl.github.io/big.js/#faq), which describes how independent constructors can be created?

Another way to avoid the save-set-reset palaver is to set the DP to the highest value needed and then use `round` if a particular operation needs a different value

    x.div(3).round(10);

The design goal is to keep the API as simple and easy to use as possible. For example, almost all methods only accept a single argument (`round` accepts two).

I ummed and ahed about whether to include optional decimal places and rounding mode parameters in the methods which involve division (div, sqrt and negative pow), and in the end decided that three parameters was just too many! For example, the aesthetic and semantic quality of the following seems poor

    y = x.div(3,2,1);

and how often would it really be used anyway?

It was a decision that could have gone either way, but when I considered it in the past it was a case of *if in doubt leave it out*.

**Comment by defunctzombie** [comment]
I was envisioning more of

```
y = x.div(3, { RM: ..., DP... });
```

I agree that use cases might not be the "everyday" but I would find it useful for methods like `toFixed` or `toPrecision` to specify the RM since those are typically used closer to the presentation layer.

**Comment by MikeMcl** [comment]
I've thought about it, and will accept the addition of a rounding mode parameter to `toExponential`, `toFixed` and `toPrecision` as I agree it would be useful and it can be done with very little additional code (keeping the library small is another important goal here).

I will also accept the addition of decimal places and rounding mode parameters to `div` only.
And in spite of what I wrote above, for consistency with `round` and `toFixed` etc. I'd prefer the `y = x.div(3,2,1);` form, rather than an using object properties.

**Comment by MikeMcl** [comment]
After further reflection, I've decided against these changes. I'm going to respect the original decisions I made when I considered these matters at length.

While an application requires, for example, different `DP` settings for different calculations then it is just a matter of always specifying the `DP` beforehand

    Big.DP = 10; x = x.div(y);

or even

    x = x.div(y, Big.DP = 10);

which doesn't seem to me to be significantly more onerous than doing 

    x = x.div(y, {DP: 10}); 

The latter has the advantage of not altering the global `DP`, but at the cost of complicating and bringing inconsistency to the API - '*Why can't I pass an options object to every method?*', '*Do I always need to specifiy the DP for division?*' etc. It would also involve having to check for the object on each call, and parse it if present, and produce an appropiate error message etc.

For users that really want to be able to specify different settings for each operation, there is also the option of redefining the relevant prototype method as required, for example,

```javascript
Big.prototype.div = (function () {
  var div = Big.prototype.div;
  return function (n, dp, rm) {
    var result,
      Big = this.constructor,
      _dp = Big.DP,
      _rm = Big.RM;
    if (dp != null) Big.DP = dp;
    if (rm != null) Big.RM = rm;
    result = div.call(this, n);
    Big.DP = _dp;
    Big.RM = _rm;
    return result;    
  }
})();
```

**Comment by defunctzombie** [comment]
Ok. I'll add tho that these globals are annoying when dealing with Big.js
instances returned from other modules I might be using. I am not always in
control of the big.js instance at the point when I want to turn it into a
string or fixed number, etc.

And they suffer from errors in forgetting to set them back. My
rounding needs for rendering might be different than needs for operators
and globals are any easy way to make that mistake.

Yes, I can monkey patch it but that is also pretty silly if I have to do
that per instance as described above.
