### ISSUE TITLE
don't use scientific notation by default

### ISSUE THREAD

**Issue by defunctzombie** [MikeMcl/big.js#53]
This caught me a bit by surprise but the `toString` methods will return results in scientific notation by default. Using an arbitrary precision library I expect output to be the full number in decimal notation. Thoughts on changing the default to not use scientific notation and/or adding a way to disable scientific notation?

Related to https://github.com/MikeMcl/big.js/pull/51 but I also expected the default behavior to be no scientific notation.

**Comment by MikeMcl** [comment]
`toString` returns scientific notation if the exponent of the Big number it is called upon is >= `TO_EXP_POS`, or <= `TO_EXP_NEG`. This works in the same way that `toString` on JS numbers returns scientific notation if the number has an exponent <= -7 or >= 21.

#51 seeks to expose these limits so they can be changed at runtime, e.g. `Big.E_POS = 20`.

`toFixed()` is available if a user always wants normal, non-scientific notation.

**Comment by defunctzombie** [comment]
@MikeMcl Right, I am aware of the open PR and the behavior of current toString(). I see that you desired to make the behavior match JS number toString(), fair.

The only real issue I have with changing the value at runtime is that it would be nice to be able to specify a way to turn off scientific notation output. Imagine a situation where I know I always want to output decimal notation and avoid picking some arbitrary `E_POS` point.

Also, thoughts on arguments to `toString` for this scientific notation to again specify on a per-call basis?

**Comment by MikeMcl** [comment]
I am not sure there would be many users who would want e.g. `1.23e+4567` to be displayed in normal notation.

In this library, the specific purpose of `toFixed()` is to always return fixed-point notation, so that is what should be used to avoid scientific notation.

I don't want to add arguments to `toString`.

I am trying to avoid feature creep, so I will be very reluctant to make any further additions at all.
