### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by pmontrasio** [MikeMcl/big.js#54]
There is a npm package called big and it's this one https://www.npmjs.com/package/big

I found it because I tried npm install big and didn't get what I expected.

You could state in the README that there is no npm package for your library and the way to install it is by downloading the files. IMHO a better way would be to rename it a create a npm package (principle of least surprise), which would also give us an easy way to keep our files up to date.

**Comment by pmontrasio** [comment]
I realized you do have a npm package, it's called big.js https://www.npmjs.com/package/big.js

I still recommend to write ```npm install big.js``` at the beginning of the README.

**Comment by MikeMcl** [comment]
Okay, done.
