### ISSUE TITLE
test method

### ISSUE THREAD

**Issue by lukescott** [MikeMcl/big.js#61]
Instead of doing something like:
```javascript
var number;
try {
  number = Big(userInput);
} catch(error) {
 // handle invalid number
}
```

It would be useful to have something like:

```javascript
if (!Big.test(userInput)) {
  // handle error
  return;
}
var number = new Big(userInput);
```

Currently I'm using something like:

```javascript
if (!/^\d+(\.\d*)?$/.test(userInput)) {
  // handle error
  return;
}
var number = new Big(userInput);
```

Which the regex doesn't necessarily cover all cases. I think I actually have a more complex one. Rather than digging up a good regex or relying on try/catch it would be nice if there was a way to validate the input using Big.

This could also be added to BigNumber or Decimal as well.

**Comment by MikeMcl** [comment]
I think that would be reasonable.

At the moment the `Big` constructor validates its input using a regex. Often the user knows the input is valid, so this is an uneccessary operation. The validation could instead be moved into a separate `test` method as you suggest, so the regex would not need to be run unless the user was unsure of an input's validity. 

I am reluctant to add further methods to the API, but I'll consider it further.
