### ISSUE TITLE
test Round method

### ISSUE THREAD

**Issue by riveryong** [MikeMcl/big.js#62]
I have test case like this:

    var t1 = “143.50”;
    var t2 = “143.10”;
    var n1 = new Number(t1);
    var n2 = new Number(t2);
    var a= new Big((n1-n2).toFixed(3));
    var b= new Big(t1-t2);
    var c= a.round(2,3);
    var d= b.round(2,3);

the result output like this:
a=0.4
b=0.4000000000000057
c=0.4
d=0.41

so, result of "c" is my expected result, but we must “toFixed(3)" befor "round(2,3)".
could you tell me how could I calculate "0.4" more sample?

**Comment by MikeMcl** [comment]
All of 

    var t1 = “143.50”;
    var t2 = “143.10”;
    var n1 = new Number(t1);
    var n2 = new Number(t2);

is irrelevant, so what we have is

    var n = "0.4000000000000057";
    var a = new Big( n.toFixed(3) );    // "0.4"
    var b = new Big(n);                 // "0.4000000000000057"
    var c = a.round(2,3);               // "0.4";
    var d = b.round(2,3);               // "0.41";

I'm not sure what it is you are having difficulty with.

When you use rounding mode `3`, `ROUND_UP`, then the digit in the second decimal place will be rounded up if there are any further non-zero digits at all, so even for example `0.400000000000000000000000000000000001` would be rounded up to `0.41`. If you don't want that behaviour, don't use that rounding mode.
