### ISSUE TITLE
Rounding to the tens/hundreds/etc place

### ISSUE THREAD

**Issue by MrDarkHorse** [MikeMcl/big.js#63]
I know you can round something to the right of the decimal.

For example, 
Big b = new Big(555.5555);
b.round(2);  // 555.56

But what if I want to do something like the following?
b.round(-1);  // 560

This doesn't appear to be supported, although it is in native Javascript.

**Comment by MikeMcl** [comment]
Yes, many JavaScript implementations support a negative value for the *fractionDigits* parameter of `Number.prototype.toFixed`.

I have considered it before, but have never took the trouble to implement it. I may include it when I refresh this library in the near future.

**Comment by jamesc892** [comment]
Bump. This would be a great addition to this library.

**Comment by MikeMcl** [comment]
Added in *v5.2.0*.
The argument to`round` can now be negative, to round to the tens/hundreds/etc place.
Note that Firefox no longer accepts a negative argument to `toFixed` and I do not want to add that here.
