### ISSUE TITLE
Lazy Evaluation

### ISSUE THREAD

**Issue by balasuar** [MikeMcl/big.js#64]
Given this example `x.div(y).plus(z).times(9).minus('1.234567801234567e+8').plus(976.54321).div('2598.11772')
x.sqrt().div(y).pow(3).gt(y.mod(z))` 

And

`A Big number is immutable in the sense that it is not changed by its methods.`

It means that above example creates something like 11 unnecessary objects. Is there plans to support a lazy evaluation?

**Comment by MikeMcl** [comment]
No, no such plans. What did you have in mind?

**Comment by AlexGalays** [comment]
Or rather, did you measure performance issues with the above code ? :)
