### ISSUE TITLE
Using fractional exponents in .pow()

### ISSUE THREAD

**Issue by barlowm** [MikeMcl/big.js#65]
Any plans to allow fractional exponents in the pow() function?
e.g. Big(2).pow(0.1) ==> !pow!

I love the library but the need for a fractional exponent when calculating a power is critical in some applications I'm working on (and some of those exponents I need to use are really weird).

Thanks

**Comment by MikeMcl** [comment]
Unfortunately, support for fractional exponents will definitely not be added here.

[decimal.js](https://github.com/MikeMcl/decimal.js) and [decimal.js-light](https://github.com/MikeMcl/decimal.js-light) do handle them though.

**Comment by barlowm** [comment]
Thanks, I did end up switching to decimal.js
