### ISSUE TITLE
Precision problems when multiplying by repeating decimal

### ISSUE THREAD

**Issue by karjaneth** [MikeMcl/big.js#68]
When multiplying a value by a fractional number like 2/3, the intuitive way to do this would be to call `some_value.times(Big('2').div(Big('3')))`, but in some cases this produces incorrect results. For example:

```javascript
var Big = require('big.js');

var nine = Big('9');
var two = Big('2');
var three = Big('3');

// results in '6.00000000000000000003'
var six_1 = nine.times(two.div(three)); // intuitive but wrong

// results in '6'
var six_2 = nine.times(two).div(three); // actually works

six_1.eq(six_2);  // false
```

The incorrect Big instances can be sanitized by converting them to Numbers and back,
but this is clumsy and I don't know if it would work in all circumstances.
```javascript
six_1 = Big(Number(six_1)); // is now '6'
six_1.eq(six_2);  // true
```

This issue doesn't occur when using Number literals:
```javascript
var nine = 9;
var two = 2;
var three = 3;

// both of these result in 6
var six_1 = nine * (two / three);
var six_2 = (nine * two) / three;

six_1 === six_2; // true
```

Perhaps this is expected behavior, but I couldn't find it documented anywhere, and it's not consistent
with other languages' arbitrary precision decimal libraries. For example, in Python 3:
```python
from decimal import Decimal

nine = Decimal('9')
two = Decimal('2')
three = Decimal('3')

six_1 = nine * (two / three)
six_2 = (nine * two) / three

six_1 == six_2  # True
```

**Comment by MikeMcl** [comment]
Python's Decimal at default precision gives 

    0.6666666666666666666666666667

for `two / three`.

Multiplying this number by `9` is obviously not `6`, unless the result is rounded. 

Python rounds the result of a multiplication to the current precision setting, but big.js does not round the result of a multiplication at all, the result is always exact. 

big.js only rounds a result if division is involved.

With big.js at its default `Big.DP` setting, `two.div(three)` is

    0.66666666666666666667

which multiplied by `6` is 

    6.00000000000000000003

as it should be.

If you want the answer to be `6` just use the `round` method to round the result to the number of decimal places required.

**Comment by rollawaypoint** [comment]
Computer in dealing with digital mathematical operations (such as the decimal), its first converted to binary again, the decimal Numbers to binary may occur in the process of precision loss, can be used by toFixed and round method comprehensive to solve this problem. For example, in javascript, we want to calculate 55.55 *100 using num = math.round (num*10000)/100 to get the desired result.
