### ISSUE TITLE
Parsing a number string with a "+" prefix

### ISSUE THREAD

**Issue by numbergames** [MikeMcl/big.js#70]
Would the slight performance hit of testing for a "+" prefix on a string passed to Big() be acceptable? Currently it throws a NaN error.

My very simplistic change at around line 190 (with the "-" sign parsing) in case it's useful to anyone else:

if (n.charAt(0) === "+") {
            n = n.slice(1);
          }

Thanks for this library and the well-written, solid source.

Added as a pull request with additional details. Sorry for duplicate pull & issue.

**Comment by MikeMcl** [comment]
Thank you, but I don't want to include this.
