### ISSUE TITLE
difficulty understanding example

### ISSUE THREAD

**Issue by godmar** [MikeMcl/big.js#72]
I'm having trouble understanding the example in the [README](https://github.com/MikeMcl/big.js/):

```javascript
x = new Big(123.4567)
y = Big('123456.7e-3')             // 'new' is optional
z = new Big(x)
x.eq(y) && x.eq(z) && y.eq(z)      // true
```

The floating point literal 123.4567 is really 123.4566999999999978854248183779418468475341796875 - why is that '.eq()' to 123456.7e-3?

It's not equal in other big decimal libraries, e.g., in Python:

```python
>>> from decimal import Decimal as D
>>> D(123.4567) == D('123456.7e-3')
False
```

nor should it be?

**Comment by MikeMcl** [comment]
What's with the question mark? Come on, don't sit on the fence. Take a view. Commit to a side.

Should the literal be interpreted as the value of its internal binary representation or, as is currently the case, as its external decimal representation? And why?

Which is more straightforward and intuitive? Which is more useful?

I notice that if the former interpretation is used then values such as `0.1` would have to be entered as strings. And also, how would the library quickly get the underlying value of a literal so it could be converted to a Big Number?

**Comment by godmar** [comment]
This is my confusion. I do not understand how you can interpret the literal as anything but its internal 64-bit binary representation (unless you write your own JavaScript interpreter that parses the input code). You simply cannot recover what the programmer passed in there unless you look at the source code, for the simple reason that after the decimal-to-binary conversion performed by the JavaScript interpreter's parser this information is gone.

Now mind you, I haven't actually studied your library - I'm looking for one - but when I saw the example I thought that either this may be broken or you're doing something magical I do not understand.

**Comment by MikeMcl** [comment]
The literal is parsed as a string. Its decimal value is taken to be its `toString` value.

Admittedly, in some cases this can cause perhaps unexpected results

```js
x = new Big( 0.7 + 0.1 );
x.toString();    // '0.7999999999999999'

y = new Big( 1.0000000000000001 );
y.toString();    // '1'
```

See the discussion of this sort of issue in the *bignumber.js* library [here](https://github.com/MikeMcl/bignumber.js/issues/11).

**Comment by godmar** [comment]
Unusual. You may want to point it out in the documentation that you rely on the semantics of Number.toString().  I hope it's well defined in the ECMAScript standard.

**Comment by MikeMcl** [comment]
Yes, see [ToString Applied to the Number Type](https://tc39.github.io/ecma262/#sec-tostring-applied-to-the-number-type).
