### ISSUE TITLE
Request: Angular 2

### ISSUE THREAD

**Issue by Squeezya** [MikeMcl/big.js#73]
Hello, Is angular 2 support a nearby future or can you guys please consider that? Thank you :D

**Comment by MikeMcl** [comment]
What is required for Angular 2 support?

**Comment by Squeezya** [comment]
I am making a project in angular 2 and I require extreme precision in my calculations as I am working with coordinates. Coordinates have 15 decimal digits.  
You can see my project here: https://github.com/Squeezya/MeiCM-MapSpike

The problem is that when I try to see if a coordinate point is on the boundary of a polygon (made with coordinate points) the javascript precision fails on some cases (with the function I am using at least).

Using this package on Angular would be nice for me in this case, as it would have auto-completes and everything, making it so much easier to work with. I would also be able to have a type Big in typescript.

**Comment by nycdotnet** [comment]
big.js has a type definition for TypeScript already.  https://github.com/MikeMcl/big.js#typescript  Beyond that, Angular is just JS so it should work normally, no?

**Comment by Squeezya** [comment]
I did not know that. Do you have an idea how I can use that in angular?

**Comment by nycdotnet** [comment]
I would try googling around for a guide on using external JS libraries with Angular 2 - perhaps one on Lodash or Underscore.   You're sure to find something.  The same technique to use those libraries should work for big.

**Comment by Squeezya** [comment]
Thank you! Will try and add the solution here, if I find one.
