### ISSUE TITLE
.pow() throws error when argument is "0" (string) or Big(0) or 0.*

### ISSUE THREAD

**Issue by aifrim** [MikeMcl/big.js#74]
The .pow function is defined in `big.js:800`

    P.pow = function (n) {
        var x = this,
            one = new x.constructor(1),
            y = one,
            isNeg = n < 0;

        if (n !== ~~n || n < -MAX_POWER || n > MAX_POWER) {
            throwErr('!pow!');
        }

        n = isNeg ? -n : n;

        for (;;) {

            if (n & 1) {
                y = y.times(x);
            }
            n >>= 1;

            if (!n) {
                break;
            }
            x = x.times(x);
        }

        return isNeg ? one.div(y) : y;
    };

Ex:

    new Big(1).pow(new Big(0));
    new Big(1).pow("0");
    new Big(2).pow(0.084);

Give:

    Uncaught Error: !pow!(…)

**Comment by MikeMcl** [comment]
I am not sure why you have included the source code of the method, or what the issue is here.

The [documentation](http://mikemcl.github.io/big.js/#pow) for the `pow` method states that its argument must be of type number. 

If you want to make an argument as to why it would be better if it accepted a string or Big then do so.

**Comment by aifrim** [comment]
First it would be nice for the methods to accept Big datatype.

Second, if the power is between 0 and 1 it throws the error.

**Comment by MikeMcl** [comment]
"It would be nice.." is unpersuasive. 

As the absolute value of the argument to `pow` must be a integer less than or equal to a million, I see no point in changing the method to also accept a Big or string.

I don't want to support floats as it would involve adding a lot of code and this is a minimalist library, instead see [decimal.js](https://github.com/MikeMcl/decimal.js) or [decimal.js-light](https://github.com/MikeMcl/decimal.js-light).

**Comment by aifrim** [comment]
Could you force the conversion from string to int?

    n = parseInt(n);

Because I supplied a `Big` that resulted from an inline formula.
Ex:

    .pow(Big from formula)

**Comment by MikeMcl** [comment]
Yes, you can use `parseInt(n) or `Number(n)` or `+n` etc. Behind the scenes that will cause `valueOf` to be called, which will return a string that will be coerced to a number.
