### ISSUE TITLE
Query regarding conversion of Big.js to Number

### ISSUE THREAD

**Issue by raghav135** [MikeMcl/big.js#75]
Firstly , thanks for the wonderful set of libraries :+1: 

I have a query regarding conversion of a big.js to a number.
For example:
I need to add 0.1 and 0.2
I do 
var a = big(0.1).plus(0.2);
Now i want to store it as a number on my object.
Currently I am doing
var n = Number(a);
which is probably doing
Number(a.toString());

I just want to know if there is any better way that i am missing.

**Comment by MikeMcl** [comment]
Thanks for the feedback.

No, there is no better way.
