### ISSUE TITLE
Recommend way for comparison of Bigs

### ISSUE THREAD

**Issue by chris-orchard** [MikeMcl/big.js#78]
What is the recommended way of comparing two Big objects for less than and greater than?

The fact that you have implemented a `valueOf` method means I can use the standard > < >= <= operators to compare but you also have [`gt`](http://mikemcl.github.io/big.js/#gt), `gte`, `lt`, `lte` functions.

As a specific example is there any difference between the following and if so is there any benefit to either approach or cases where they'd work differently?

    var b1 = new Big('1')
    var b2 = new Big('2')
    
    b1 < b2  // true
    b1.lt(b2) // true

**Comment by MikeMcl** [comment]
The recommended way is to use the comparison methods `gt`, `lt` etc.

It is fine though to use the standard operators as long as the values to be compared can be represented exactly as JavaScript numbers. 

If they can't then, for example
```js
x = new Big('12345678987654320');
y = new Big('12345678987654321');

x.gte(y);    // false    (correct)
x >= y       // true     (wrong)
```

**Comment by chris-orchard** [comment]
Thanks for clarifying this. That makes sense.
