### ISSUE TITLE
Something a little weird with round and powers of 10

### ISSUE THREAD

**Issue by Xotic750** [MikeMcl/big.js#89]
I was poking around a little and noticed something strange (may be intended) in the round function.
If I create a Big(100), it looks like this.
```
 { [String: '100']
  s: 1,
  e: 2,
  c: [ 1 ],
  constructor: 
   { [Function: Big]
     DP: 20,
     RM: 1,
     NE: -7,
     PE: 21,
     Big: [Circular],
     default: [Circular] } }
```
If I now call .round and watch what is happening, then .round increases the length of .c and makes it a sparse array
```
...
    i = x.e + dp + 1;
...
      // Remove any digits after the required decimal places.
      xc.length = i--;
```
and the content then looks like
```
 { [String: '100']
  s: 1,
  e: 2,
  c: [ 1, , ],
  constructor: 
   { [Function: Big]
     DP: 20,
     RM: 1,
     NE: -7,
     PE: 21,
     Big: [Circular],
     default: [Circular] } }
```
Of course this doesn't create a problem because these holes get removed just after
```
      // Remove trailing zeros.
      for (i = xc.length; !xc[--i];) { xc.pop(); }
```
but it does seem a little strange to me to do this?

**Comment by MikeMcl** [comment]
Yes, it does seem inefficient to create a sparse array unnecessarily.
I am not sure why the code doesn't first check that `i < xc.length` before setting the `xc.length` to `i`.
It may be because I was trying to use as little code as possible.
I'll look into it.

**Comment by Xotic750** [comment]
While I'm looking at that area, it might be more (micro) efficient to do the following instead of multiple pops? I haven't tested it or anything.
```
// Remove trailing zeros.
for (i = xc.length; !xc[--i];) {}
xc.length = i + 1;
```

**Comment by MikeMcl** [comment]
I've added a `i < xc.length` check.

It's useful for calls like `new BIg(1000000).round(1000000)` which are now much more efficient.

Thanks for pointing it out the ineffciency.
