### ISSUE TITLE
Operation configuration isolation

### ISSUE THREAD

**Issue by srcspider** [MikeMcl/big.js#9]
This is mainly for the rounding option. Right not it's global, so unless I always want 0, 1 or 2 everywhere it's always possible to mess it up due to ajax potentially triggering a chain that executes one while another is running somewhere else.

eg.

```
Big.DP = 0;
Big.RM = 1;
var x = Big('7'); // RM is 1
var math = BigMath({'RM': 0}); // original defaults for others
var y = math.Big('7'); // RM is 0

console.log(x.div(2)); // "4"
console.log(y.div(2)); // "3"

var z = Big('2'); // RM is 1
console.log(y.div(x)); // "3" RM of a left part is always used
```

For reference, the following:

```
var math = {};
math['Big'] = $.extend({}, Big);
```

Will not work; because it's a function. But even if cloning the object worked, having the functionality built in may be more reliable/desirable.

**Comment by Xotic750** [comment]
Have further fixed this in my [fork](https://github.com/Xotic750/big.js) along with a fix for `TO_EXP_NEG` and `TO_EXP:POS`, which also had the same issue. Not written any tests for it.
