### ISSUE TITLE
what is the difference between big.js and big.mjs?

### ISSUE THREAD

**Issue by jackzhp** [MikeMcl/big.js#91]
Please mention the difference between big.js & big.mjs.

jack

**Comment by MikeMcl** [comment]
The only difference is in how they are loaded.

The former is an UMD module, the latter an ES module.

*big.mjs* can be loaded in an HTML document in a browser using 

```html
<script type="module" src="big.mjs"></script>
```

or in Node.js, using the `--experimental-modules` flag, with

```js
import Big from './big.mjs';
// or just
import Big from './big';
```

*big.mjs* can also be used with an ES6 transpiler,

**Comment by dandv** [comment]
@jackzhp, see https://medium.com/@dandv/publishing-native-es-modules-with-node-v8-5-0-730736e0f612

This can be closed now perhaps?

Michael, thanks for the great module!

**Comment by MikeMcl** [comment]
@dandv 

Cheers!
