### ISSUE TITLE
Error: Uncaught TypeError: Big is not a constructor

### ISSUE THREAD

**Issue by alanshaw** [MikeMcl/big.js#96]

**Comment by alanshaw** [comment]
To expand, the issue we were having is that in webpack `require('big.js')` looked at the `module` field and gave us `big.mjs` meaning that to use it you'd have to `require('big.js').default` (see https://github.com/webpack/webpack/issues/4742).

When https://github.com/MikeMcl/big.js/pull/97 is released the browser will now get the commonjs big.

In case anyone else stumbles on this issue, you can configure webpack to ignore the `module` field so that _none_ of your dependencies use esmodules by setting [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) to just `['browser', 'main']`.

**Comment by MikeMcl** [comment]
Thanks for the info, Alan. I've published the fix in *v5.1.2*.
