### ISSUE TITLE
There isn't  a conversion function ，converting the result to the number type

### ISSUE THREAD

**Issue by xiechuanlong** [MikeMcl/big.js#99]
1. There isn't  a conversion function ，converting the result to the number type.  for example:  if there is a toNumber function, Big(4).div(2).times(2).toNumber() will more convent.
2.  Why don't you consider Big('')  equal to Big('0').

**Comment by MikeMcl** [comment]
1.
This has come up before, see #21. To convert a Big to a number you can use, for example
```js
x = Big(1234.567)
+x         // 1234.567
Number(x)  // 1234.567
```
2. 
Notwithstanding `Number("") === 0`, the empty string isn't a number;
it is quite likely to be a mistake by the programmer.

**Comment by xiechuanlong** [comment]
Ok, thank you for your answer.
